### ISSUE TITLE
The replicator and commit hooks

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#15]
On a receiving node, are commit hooks run when data is reapplied? If so, that's a bug.

**Comment by per-samuelsson** [comment]
The current environment I have makes it a bit hard to 100% decide on this, but as far as I can tell, it look really much as if hooks actually *do* run as part of receiving incoming transactions. In that case, that's kind of a showstopper.

I think I'll need to spend some time trying to start fresh with a simplified environment to tell for sure, if no one has any answer to this.

**Comment by linkdata** [comment]
CC @eriohl @bigwad

**Comment by bigwad** [comment]
I believe, hooks get called as receiver commits ordinary transaction. Why do you consider this as a showstopper? To fix it we may introduce parameter to Db.Transact to tell TransactionManager not to call hooks

**Comment by dan31** [comment]
The classical row/record-based style replication explains not to play triggers on a replica, since they are already played on the master resulting in new rows (within a correct range) which are a matter of replication themselves. I believe we do exactly that style of replication, hence we have to suppress playing the commit hooks on the replica. In that respect, not having such is a showstopper. @per-samuelsson told me exactly this flag which @bigwad suggests was presented in Heads 1.x transactions (they had custom-made replication). @bigwad @eriohl would it be possible for you to provide the flag during this week? (I believe @bigwad can do this though check the change with @eriohl as usual). We need to handle a full-blown demo of the replicator in the beginning of next week. My only concern is that it isn't that beautiful to overload Db.Transact API with the flag to have passed every time (even if with a provided default false). @per-samuelsson @bigwad @chrhol maybe you could come up with some nicer way to settle this parameter on/off?

_P.S. We all know that setting up replicas today (in any DB) is a nice way to shoot yourself in a leg. Different DB vendors provide guns of different shape and style, yet all they are still guns. It would not be possible for us to provide something else then a sort of gun (yet we aim to make it of lesser harmfulness and/or a nice set of safety cut-outs). Hence we assume that one doesn't try to have different sets of commit hooks on master and replica and then amusing with the diverged results, and also one carefully tracks to replicate the side-effect classes of the commit hooks (if the replication logic includes any sort of filtering)._

**Comment by per-samuelsson** [comment]
> Why do you consider this as a showstopper?

Because of what @dan31 summarize above. It's plain wrong. It risk breaking data integrity.

> To fix it we may introduce parameter to Db.Transact to tell TransactionManager not to call hooks.

Yes, we had that in earlier versions of the kernel. The ability to configure a transaction not to run through hooks. It will be such a rare case (basically just used for cases like this, to support replicas), so we should be careful not to polite or standard API's with it. 

I vote that we either switch the replicator to use something like `Transaction.New().SetFlags(TransactionFlags.NoHooks)` (pseudo-code). Or if we really want to preserve the goodies with using scopes and lambdas, we introduce a variant of `Db.Transact` in some obscure namespace, like `Starcounter.Advanced`, and in the form of some other named method, like `Db.TransactWithConfig((transactionConfig) => { config.Set(...); [and scope here})`

**Comment by eriohl** [comment]
We had this in earlier versions of the kernel yes (disable commit hooks on transaction create). Was also used to disable commit hooks on commit (so that no new commit hooks callbacks are generated after starting to process commit hooks). However: Kernel no longer support commit hooks. Implementation is all in client now. This flag needs to be managed there as well.

**Comment by Starcounter-Jack** [comment]
I vote for a variant of Db.Transact in an obscure namespace.

**Comment by per-samuelsson** [comment]
>  This flag needs to be managed there as well.

I was thinking this would be done *only* in outer layers, not in the kernel at all. Can you clarify "as well"?

**Comment by eriohl** [comment]
Since commit hooks are managed in client this flag disabling commit hooks needs to be managed in the client as well. Just trying to clarify that this is not a kernel issue which seems to be implied.

**Comment by linkdata** [comment]
Today the `LogApplicator` exposes the `Apply(TransactionData)` member, which you run inside your own `Db.Transact(Action)`. A natural way of hiding this fairly log-writer-specific functionality of not calling commit hooks would be to have a `LogApplicator.Transact(TransactionData, Action)` that would do whatever is needed to get the expected behaviour when applying log transaction data.

**Comment by bigwad** [comment]
Even if we extend LogApplicator's interface, we should provide some means to instruct transaction manager to not call hooks. So as I see, @linkdata's suggestion only simplifies LogApplicator's client and still requires changes to Db.Transact.
And I'd like not to do it since I consider LogApplicator as not only replication helper, but as a general helper to apply changes to db not bothering with database classes, reflection etc. See https://github.com/Starcounter/Starcounter/issues/3020

**Comment by dan31** [comment]
> Just trying to clarify that this is not a kernel issue which seems to be implied.

True, I forgot you've done the code but you've done it in a way that relies on a codehost logic. Which I believe is more relevant, since only in codehost we have the trigger code itself, no code – no trigger, hence a codehost deal. As I understand, there is some notification mechanism in kernel that codehost relies on there and thus can suppress? (when it was done I didn't quite understand how it works).

@bigwad You are right that log manager isn't only a replication helper. @bigwad what alternative scheme you do suggest? We need a concrete scheme today or tomorrow. @chrhol I believe here is needed your assistance in changes to ```Db.Transact``` correspondingly, would you help?

**Comment by per-samuelsson** [comment]
> Since commit hooks are managed in client this flag disabling commit hooks needs to be managed in the client as well. Just trying to clarify that this is not a kernel issue which seems to be implied.

Well, it's again the *"as well"* I don't understand. Why would the kernel have to be involved *at all*? That's what I'm trying to say.

**Comment by bigwad** [comment]
> what alternative scheme you do suggest

As it was discussed - add specific overload to Db.Transact and call it from the replicator.
I may do it myself or leave it to @chrhol as you asked him to do it.

**Comment by per-samuelsson** [comment]
> As I understand, there is some notification mechanism in kernel that codehost relies on there and thus can suppress? (when it was done I didn't quite understand how it works).

No, the kernel just now support iteration of pending transactions. And the code host consume that. So on every commit (originating in the managed API), the transaction content is iterated and installed hooks are invoked. No notification mechanisms exist.

(Disclaimer: this is the design we decided on at least, and as I've understood it, that's how it all was re-implemented in **pnext**).

**Comment by per-samuelsson** [comment]
When choosing between at what level to support suppression of hooks, I favor my initial suggestion rather than making it "log applicator specific". 

The simple reason being that such feature could be usable in some other future scenario we don't know about, and then it's better to have it in a standard (but "advanced") API. After all, the feature is not really exotic, but rather quite straight-forward, so I think it's fine to support it as such.

**Comment by eriohl** [comment]
> Well, it's again the "as well" I don't understand. Why would the kernel have to be involved at all? That's what I'm trying to say.

It shouldn't be. As I understood it @dan31 suggested that we should add support for setting a flag to suppressing commit hooks in the kernel (like in previous versions). I then remarked that this is not a kernel issue an longer (commit hooks is managed by client and so this flag should be as well).

**Comment by per-samuelsson** [comment]
> It shouldn't be.

Good. Then we understand eachother. This is a pure "outer" feature, has nothing to do with the kernel.

**Comment by dan31** [comment]
@bigwad Surely do, only agree with @chrhol what's the best form on API
level (doesn't matter who, matters the agreement between involved parts)

**Comment by bigwad** [comment]
Done in ignorehooks branch.
Would be good if someone review this stuff. Going to merge it tonight.

**Comment by bigwad** [comment]
Pushed in pnext.
Passing it to  @linkdata to adopt replicator to use unhooked transactions when appropriate.

Usage:
```
Db.Advanced.Transact(
    new Db.Advanced.TransactOptions { applyHooks = false },
    <transaction delegate>
);

```

**Comment by per-samuelsson** [comment]
> Pushed in pnext.

Great @bigwad.

**Comment by per-samuelsson** [comment]
> Passing it to @linkdata to adopt replicator to use unhooked transactions when appropriate.

Its just [this single instance](https://github.com/Starcounter/Replicator/blob/4383cb9b92efeda647fab14974980308d7661043/Replicator.cs#L500), right @linkdata? As far as I could tell, all other transactions are for replication metadata and config (which wouldn't be hooked except by "us"). Can I make the change?

**Comment by linkdata** [comment]
I was planning to hold off until the next nightly is published. But yes, that is the call site.

**Comment by per-samuelsson** [comment]
> I was planning to hold off until the next nightly is published. But yes, that is the call site.

Pushelipushed.
