### ISSUE TITLE
Refactor replicator into app + lib?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#17]
Would that make sense, in the light of that we are planning to move replication configuration out from the database?

If so, app suites could optionally include replication as a "built in" feature, by means of just referencing the library and enable/activate it as part of some other entrypoint, like

```cs
void Main() {
  SetupMyStandardAppStuff();
  // Setup replicator, parent IP and port, and run it
  new ReplicationEngine(new IpAddress(127.0.0.1), 8085).Run();
}
```

And `Replicator.exe` could just do something similar to that.

/cc @linkdata WDYT? (Feel free to just close it if you think its nonsense)

**Comment by linkdata** [comment]
As a systems administrator, having apps starting their own replicators (possibly out of your control) could be a big headache. You really want full control over that. But having the main application be as minimal as possible is a good idea since that will minimize merge conflicts when people fork the repo to roll their own replicator.

Closing this since the idea has been received and understood.
